/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CustomRangePicker: typeof import('./components/CustomRangePicker.vue')['default']
    DateFrom: typeof import('./components/parts/DateFrom.vue')['default']
    DatePicker: typeof import('./components/parts/DatePicker.vue')['default']
    DateTo: typeof import('./components/parts/DateTo.vue')['default']
    ModeSelect: typeof import('./components/parts/ModeSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ValueInput: typeof import('./components/parts/ValueInput.vue')['default']
  }
}
